{
 "title": "Velocity",
 "time": { "from": "now-12h", "to": "now+1h" },
 "panels": [
  {
   "title": "Route #0",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "SELECT LAST(speed) FROM traffics.velocity WHERE device_id=0"
    },
    {
     "formatType": "Time series",
     "sql": "SELECT LAST(pred) FROM traffics.predicts WHERE device_id=0"
    }
   ]
  },
  {
   "title": "Route #5",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "SELECT LAST(speed) FROM traffics.velocity WHERE device_id=5"
    },
    {
     "formatType": "Time series",
     "sql": "SELECT LAST(pred) FROM traffics.predicts WHERE device_id=5"
    }
   ]
  },
  {
   "title": "Route #8",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "SELECT LAST(speed) FROM traffics.velocity WHERE device_id=8"
    },
    {
     "formatType": "Time series",
     "sql": "SELECT LAST(pred) FROM traffics.predicts WHERE device_id=8"
    }
   ]
  },
  {
   "title": "Route #14",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "SELECT LAST(speed) FROM traffics.velocity WHERE device_id=14"
    },
    {
     "formatType": "Time series",
     "sql": "SELECT LAST(pred) FROM traffics.predicts WHERE device_id=14"
    }
   ]
  },
  {
   "title": "Route #17",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "SELECT LAST(speed) FROM traffics.velocity WHERE device_id=17"
    },
    {
     "formatType": "Time series",
     "sql": "SELECT LAST(pred) FROM traffics.predicts WHERE device_id=17"
    }
   ]
  },
  {
   "title": "Route #25",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "SELECT LAST(speed) FROM traffics.velocity WHERE device_id=25"
    },
    {
     "formatType": "Time series",
     "sql": "SELECT LAST(pred) FROM traffics.predicts WHERE device_id=25"
    }
   ]
  },
  {
   "title": "Route #0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "SELECT AVG(speed) FROM traffics.velocity WHERE device_id=0 AND ts >= NOW-24h INTERVAL(1m)"
    },
    {
     "formatType": "Time series",
     "sql": "SELECT AVG(pred) FROM traffics.predicts WHERE device_id=0 AND ts >= NOW-24h INTERVAL(1m)"
    }
   ]
  },
  {
   "title": "Route #3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "SELECT AVG(speed) FROM traffics.velocity WHERE device_id=3 AND ts >= NOW-24h INTERVAL(1m)"
    },
    {
     "formatType": "Time series",
     "sql": "SELECT AVG(pred) FROM traffics.predicts WHERE device_id=3 AND ts >= NOW-24h INTERVAL(1m)"
    }
   ]
  },
  {
   "title": "Route #5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "SELECT AVG(speed) FROM traffics.velocity WHERE device_id=5 AND ts >= NOW-24h INTERVAL(1m)"
    },
    {
     "formatType": "Time series",
     "sql": "select AVG(pred) from traffics.predicts where device_id=5 and ts >= NOW-24h INTERVAL(1m)"
    }
   ]
  },
  {
   "title": "Route #8",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "SELECT AVG(speed) FROM traffics.velocity WHERE device_id=8 AND ts >= NOW-24h INTERVAL(1m)"
    },
    {
     "formatType": "Time series",
     "sql": "select AVG(pred) from traffics.predicts where device_id=8 and ts >= NOW-24h INTERVAL(1m)"
    }
   ]
  },
  {
   "title": "Route #17",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "SELECT AVG(speed) FROM traffics.velocity WHERE device_id=17 AND ts >= NOW-24h INTERVAL(1m)"
    },
    {
     "formatType": "Time series",
     "sql": "select AVG(pred) from traffics.predicts where device_id=17 and ts >= NOW-24h INTERVAL(1m)"
    }
   ]
  },
  {
   "title": "Route #14",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "SELECT AVG(speed) FROM traffics.velocity WHERE device_id=14 AND ts >= NOW-24h INTERVAL(1m)"
    },
    {
     "formatType": "Time series",
     "sql": "select AVG(pred) from traffics.predicts where device_id=14 and ts >= NOW-24h INTERVAL(1m)"
    }
   ]
  },
  {
   "title": "Route #21",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "SELECT AVG(speed) FROM traffics.velocity WHERE device_id=21 AND ts >= NOW-24h INTERVAL(1m)"
    },
    {
     "formatType": "Time series",
     "sql": "select AVG(pred) from traffics.predicts where device_id=21 and ts >= NOW-24h INTERVAL(1m)"
    }
   ]
  },
  {
   "title": "Route #25",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "SELECT AVG(speed) FROM traffics.velocity WHERE device_id=25 AND ts >= NOW-24h INTERVAL(1m)"
    },
    {
     "formatType": "Time series",
     "sql": "select AVG(pred) from traffics.predicts where device_id=25 and ts >= NOW-24h INTERVAL(1m)"
    }
   ]
  }
 ]
}